### ISSUE TITLE
Graph Accuracy  not displayed

### ISSUE THREAD

**Issue by SahadevPoudel** [ssrp/Multi-level-DCNet#1]
I have two question
1. After finishing training , it saves model but it is not displaying training accuracy and validation accuracy.
 The given message is displayed _"No handles with labels found to put in legend._"  why?

2. If i have to train this model on large size data (128 *128), for example medical data, then can you suggest something about changing parameters in a network?

**Comment by ssrp** [comment]
Hi @sahadev123, here are my answers:
1. I guess you are referring to the "plot_log" function at the end after saving the model. I'll have a look at the code again, although I'd recommend using TensorBoard to visualize the performance. Thanks!
2. For the medical data, I am not sure how to answer this because it depends on the dataset properties and the features you want to capture. One sure thing is the fact that the model size will definitely increase because the number of primary capsules is dependent on the spatial size of the feature map. For the brain tumor dataset, we used a size of 64x64 input and created the multi-level dcnet model. If you want some idea on how to use capsule networks on medical data, Afshar et al., ICIP 2018 have experimented with some network parameters and compared the results. Once you get some idea from that, you could try implementing a DCNet on the same, by replacing the conv-layers with a dense block.
