### ISSUE TITLE
AttributeError: module 'keras.layers' has no attribute 'Merge'

### ISSUE THREAD

**Issue by shrybht** [ssrp/Multi-level-DCNet#3]
In dcnet.py;
line 80: ` decoderFinal.add(layers.Merge([decoder.get_layer('zero_layer'), decoder.get_layer('one_layer')], mode='concat'))`

I'm facing the error:
`AttributeError: module 'keras.layers' has no attribute 'Merge'`

Could you please help me with this?

**Comment by ssrp** [comment]
Downgrade Keras version to 2.0.7 and it should work.

**Comment by shrybht** [comment]
Thank you.
I have a general question. May I know approximately how long did the model 3leveldcnet take to complete training on CIFAR10 for 500 epochs?

**Comment by ssrp** [comment]
Hi, thanks for your question. Actually, we never tried training a 3-level DCNet for 500 epochs (for any dataset).

Given that the CapsNets actually take a long time to converge, I'd like to see the results of our model trained for 500 epochs. We could achieve comparable results under ~100 epochs for most datasets (because of the skip connections -- better gradient flow).
If we perform such experiment, we'll add the results on GitHub for sure. Thanks!
